title: "Christoph Mies"
subtitle: "IT Architect"
description: "Blog · Publications · Professional Journey"
url: "https://christoph-mies.de"
og_image: /assets/images/author-photo.jpg # image used when sharing links. Can be a logo or portait. ATTENTION: also check og_image when updating!

minimal_mistakes_skin: "default" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
encoding: utf-8 # no official jekyll standard, but: might help and will not break anything


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
locale: en_GB
timezone: Europe/Berlin # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

plugins:
  - jekyll-paginate # Automatically splits your post list into smaller chunks (e.g., 5 or 10 posts per page) and creates the "Next/Previous" navigation at the bottom.
  - jekyll-sitemap # It automatically generates a sitemap.xml file, which tells search engines like Google exactly which pages exist
  - jekyll-gist # Instead of copying long code blocks into your Markdown, you just use a simple tag like {% gist ID %}. It renders the code beautifully with syntax highlighting directly from GitHub.
  - jekyll-feed # It creates an Atom/RSS feed (usually at /feed.xml), Whenever you post a new summary, it automatically pops up in their feed readers.
  - jemoji #  It brings GitHub-style emojis to your site like :books: or :triangular_ruler: representing emoji images 📚 📐
  - jekyll-include-cache # It is a performance booster for your site's build process.

include:
  - _pages

# the following files are not available via the website
exclude:
  - README.md
  - CNAME
  - LICENSE
  - scripts/
  - .vscode/
  - Gemfile
  - Gemfile.lock
  - exclude/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true # alculates the estimated reading time (e.g., "3 min read") and displays it at the top of the article.
      comments: true # Activates the comment section below the post. You must also configure a provider _config.yml.
      share: true # Displays social media buttons (Twitter, Facebook, LinkedIn, etc.), allowing readers to share your post with a single click.
      related: false # Enables the "You May Also Enjoy" section. Displays similar posts here (based on shared tags or categories).
      author_profile: true
      sidebar:
        nav: main
        position: left
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: main
        position: left

# site properties
email: www-christoph-mies-de@web.de # ATTENTION: Also check mail adress in author-info when changing!

author:
  name   : "Christoph"
#  bio    : "Here I am sharing my projects and thoughts."
  avatar : /assets/images/author-photo.jpg # Path to photo. ATTENTION: also check og_image when updating!
  location: "Lohmar, Germany"
  links:
    - label: Email
      icon: "fas fa-square-envelope"
      url: "mailto:www-christoph-mies-de@web.de" # ATTENTION: Also check mail adress in site properties when changing!
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://de.linkedin.com/in/christoph-mies-459042177"
    - label: XING
      icon: "fab fa-fw fa-square-xing"
      url: "https://www.xing.com/profile/Christoph_Mies3"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com"

atom_feed: 
  hide: true # not rendered anyway as long as search is active. So I put RSS feed to footer explicitly

comments:
  provider: custom

footer:
  extra_footer_content: '© 2026 Christoph Mies &#124; <a href="/feed.xml"><i class="fas fa-square-rss" style="color: #ee802f;"></i> RSS Feed</a> &#124; <strong><i class="fas fa-screwdriver-wrench"></i> As of March 2026: Site under construction <i class="fas fa-screwdriver-wrench"></i></strong> &#124; <a href="/legal/"><i class="fas fa-scale-balanced"></i> Imprint, disclaimer and privacy policy</a> &#124; <a href="/legal/"><i class="fas fa-scale-balanced"></i> Impressum, Datenschutzerklärung und Haftungsausschluss</a>'
